### ISSUE TITLE
Builder (Automated) Checklist

### ISSUE THREAD

**Issue by MikePreston17** [MikePreston17/nugs#8]
- [ ] Builds:
    - Greedy Algorithm
        a. Favors more expensive/least expensive (toggle this as a mode)
        b. Introduce slots (grip, LPK, lower, etc.)...make custom builder object for this
        c. Display the fully built AR, within price.
        d. Dipspay a slider bar for budget.
        e. Add a Randomizer button.
        f. Finish the Types and Categories in Airtable (build the form for this later)
- [ ] Build Checklist (todolist) on Builds and Builds and Shipping

**Comment by MikePreston17** [comment]
- [ ] Vuetify quick integration, if possible [link](https://next.vuetifyjs.com/en/getting-started/installation/)
- [ ] Finish Builder alg:
	- [ ] Sort Parts in Grid(s) by Type
	- [ ] Scroll down after each type is picked
	- [ ] Stash the build id in localStorage
	
	- [ ] Show the completed list w/ bugdet
	- [ ] Diplay a rolling floating bar to the left, showing the % done and running total (msrp)
	- [ ] Show a button for downloading the list of links
	- [ ] Show a button for Saving this build to profile & save the full build from 
	- [ ] (Omit vuex calls in Builds.vue, for now - retain Setting and Profile in Vuex.)	
	- [ ] Once again, stash the build Id when the user is finished with their build
